// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("ConvertXml")]
[assembly: AssemblyDescriptionAttribute("Tool for convert from a .Net object to XML")]
[assembly: GuidAttribute("A539B42C-CB9F-4a23-8E57-AF4E7CEE5BAA")]
[assembly: AssemblyProductAttribute("ConvertXml")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
[assembly: AssemblyVersion("0.0.1.*")]